Resolve RFL "PR 템플릿 수정"
hanghae-team6/react-fetching-library pull request #33
Opened 2024-04-18 12:50 UTC by JungMinSeung

## 무엇을 위한 PR인가요?

- [ ] 기능 추가
- [ ] 스타일
- [ ] 리팩토링
- [ ] 문서 수정
- [ ] 버그 수정
- [ ] 테스트 코드 작성
- [ ] 기타

## 왜 코드를 추가/변경하였나요?

- PR 템플릿 위치를 .github 바로 밑으로 수정
- 테스트 코드에 대한 체크박스 추가
- 스크린샷 삭제

## 기대 결과

-

## 리뷰어에게 전달 사항

-

## 관련 이슈 번호

close : #

2024-04-18 12:51 UTC, ssssssjay approved these changes
감사합니당

2024-04-18 12:52 UTC, mandarin-sep requested changes
dev 로 바꿔주세요 !

2024-04-18 13:16 UTC, slamdunk11 approved these changes
수정 감사합니다!

2024-04-19 02:12 UTC, JungMinSeung commented
리뷰 감사합니당 사고칠뻔했네요 ㅎㅎ

2024-04-24 11:58 UTC, ssssssjay approved these changes
확인했습니다수정사항

2024-04-24 12:43 UTC, mandarin-sep approved these changes

2024-04-25 11:01 UTC, merged