useQuery, useMutation 작성
hanghae-team6/react-fetching-library pull request #37
Opened 2024-05-08 12:58 UTC by JungMinSeung

## 무엇을 위한 PR인가요?

- [x] 기능 추가
- [ ] 스타일
- [ ] 리팩토링
- [ ] 문서 수정
- [ ] 버그 수정
- [x] 테스트 코드 작성
- [ ] 기타

## 왜 코드를 추가/변경하였나요?
- useQuery 작성
  - 명세
    - fetching
    - caching
    - status 관리
    - invalidate 기능
- useMutation 작성
  - 명세
    - mutate
    - onError, onSuccess, onMutate, onSettled (핸들러 함수 작성) 
- 테스트 코드 작성 

## 기대 결과
- useQuery 테스트 결과
<img width="660" alt="스크린샷 2024-05-12 오후 8 50 16" src="https://github.com/hanghae-team6/react-fetching-library/assets/59415379/f3d9d04f-78de-4525-a492-76c66145b2eb">

- useMutation 테스트 결과
<img width="666" alt="스크린샷 2024-05-12 오후 8 50 27" src="https://github.com/hanghae-team6/react-fetching-library/assets/59415379/1b6bdfa1-f92d-4341-a97d-59433f9cb116">

## 리뷰어에게 전달 사항

- 코드 오류 확인 부탁드립니다.
- 더 필요한 테스트 케이스가 있다면, 코멘트 부탁드립니다.

## 관련 이슈 번호

close : #21

2024-05-13 11:48 UTC, slamdunk11 commented on src/hooks/useQuery.ts
> +    }
개인적으로 initialize를 fetchFn에 넣는 게 어떨까합니다!

invalidateQueries도 결국 fetchFn을 실행하는 거라
상태가 초기화되고 -> setStatus(~~) 흐름을 따르는 게 좋을 거 같아서요!

2024-05-13 11:48 UTC, slamdunk11 commented on src/hooks/useQuery.ts
> +
깔끔하게 initialize로 초기화하는 친구들 묶는 거 좋네여!

2024-05-13 11:48 UTC, slamdunk11 commented on src/hooks/useMutation.ts
> +};
useQuery에서 이렇게 사용했던 것처럼
useMutation에서도 통일감있게 설정하면 좋을 거 같습니다!
```
 isLoading: status === 'pending',
    isSuccess: status === 'success',
    isError: status === 'error',
```
반대로 useMutation에 설정된
onError, onSuccess를 useQuery에 넣는 것도 좋을 거 같아요!

2024-05-13 11:48 UTC, slamdunk11 commented on src/__tests__/useQuery.test.tsx
> +  it('should handle queries', async () => {
아마 이 테스트는 쿼리키에 따라 각각 잘 저장되었는 지를 테스트하는 거 같습니다!
위의 테스트와 같은 메시지라서 메시지 내용을 바꾸면 좋을 거 같아요!

영어는 파파고...!

```
should have a result value stored in the query key
```

2024-05-13 11:48 UTC, slamdunk11 commented on src/__tests__/useQuery.test.tsx
> +
추가적인 api 호출 없이 캐시된 데이터를 사용하는 지 확인하는 테스트인 거 같습니다!
``` 
await waitFor(() => expect(mockFetchFn).toHaveBeenCalledTimes(1));
```
얘를 renderHook마다 써줘서 api 호출횟수가 1로 유지되는 지 체크하면 더 좋을 거 같아요!

2024-05-13 11:48 UTC, slamdunk11 commented on src/__tests__/useMutation.test.tsx
> +  });
onSettled는 제일 마지막에 실행되는 걸로 알고 있습니다!
앞부분에 isError, isLoading 등 상태가 어떻게 변했는지 먼저 확인하는 코드를 넣어주면 더 좋을 거 같아요!

2024-05-13 12:34 UTC, ssssssjay commented on src/hooks/useQuery.ts
> +  const queryKeyString = JSON.stringify(queryKey);
`type TQueryKey = unknown[];` 만약 이 부분이 `string[]`이었다면 괜찮을 것 같은데요,
어떤 파라미터가 들어올지 모르기에 `tanstackQuery`에서 사용하는 키를 해싱하는 함수를 참고하면 좋을 것 같아요!

참고하시면 좋을 것 같습니다 😀
https://github.com/hanghae-team6/react-fetching-library/pull/38/files#diff-5acab41990585fa68ae01ff7b2e2915628d19237840c3061b31fcadc1c0f09b8

2024-05-13 12:41 UTC, ssssssjay requested changes
쿼리 키 해싱함수 부분 보완한다면 좋을 것 같습니다...! 코멘트는 남겨두었어요

2024-05-13 12:43 UTC, ssssssjay reviewed
쿼리 키 해싱함수 부분 보완한다면 좋을 것 같아요. 코멘트는 남겨두었습니다.

2024-05-14 03:55 UTC, mandarin-sep approved these changes

2024-05-14 03:55 UTC, mandarin-sep commented on src/__tests__/useMutation.test.tsx
확실히 mutation을 테스트 하는게 그냥 query 를 테스트 하는거보다 생각해야 할 게 좀 더 많은거 같네요. 좋은거 같습니다!

2024-05-14 03:55 UTC, mandarin-sep commented on src/hooks/useMutation.ts
> +};
onSuccess 같은 값이 props 로 넘어 오면 isSuccess 같이 전달받은 상태 값은 그냥 받은 값을 그대로 넘겨주는게 되니까 없어도 되지않을까요?

2024-05-14 11:43 UTC, JungMinSeung commented on src/hooks/useQuery.ts
> +    }
수정했습니다~ 감사합니다!

2024-05-14 11:49 UTC, slamdunk11 approved these changes
LGTM~🚀🚀🚀

2024-05-14 11:49 UTC, ssssssjay approved these changes
코드 수정해주신 부분 잘 보았습니다. 고생하셨습니다.

2024-05-14 11:49 UTC, merged

2024-05-16 11:58 UTC, JungMinSeung commented on src/hooks/useQuery.ts
> +  const queryKeyString = JSON.stringify(queryKey);
적용했습니다! 감사합니다~